log2console: true
timesFilePath: "manifest.yaml"

# Golang date formation
#    year: 2006
#   month: 01
#     day: 02
#   hours: 15
# minutes: 04
# seconds: 05
logging:
  script: "script_log/shipperLogs_{200601021504}.log"
  files: "script_log/processedFiles_{200601021504}.log"

ftps:
- name: "test"
  hostname: "127.0.0.1"
  port: 21
  username: "ftpuser"
  password: "passwd"
  protocol: "ftp"

# Shipper modes:
#  import
#  export
services:
- name: "service name"
  ftpConfig: [test]
  mode: import
  sourceFolder: "asd"
  destinationFolder: "asd"
  filePrefix: "file-"
  fileExtension: "txt"
  historyFolder: ""
  maxTime: 123
  windowLimit: 1
