log2console: true
timesFilePath: "local_devel/loader_manifest.yaml"

# Golang date formation
#    year: 2006
#   month: 01
#     day: 02
#   hours: 15
# minutes: 04
# seconds: 05
logging:
  script: "local_devel/script_log/loader-logs_{200601021504}.log"
  files: "local_devel/script_log/loader-processedFiles_{200601021504}.log"

# Loader modes:
#  compress
#  cleaner
services:
- name: "cleaner service"
  mode: cleaner
  sourceFolder: "local_devel/cleardata/files_1min"
  destinationFolder: ""
  filePrefix: "min1_"
  fileExtension: "log"
  maxTime: 2
  windowLimit: 1

- name: "compress service"
  mode: compress
  sourceFolder: "local_devel/cleardata/files_1min"
  destinationFolder: "local_devel/cleardata/files_1min/archive"
  filePrefix: "min5_"
  fileExtension: "log"
  maxTime: 2
  windowLimit: 1
